//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gb_raw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int answerID { get; set; }
        public int questionID { get; set; }
        public int questionResult { get; set; }
        public Nullable<bool> isModelAnswer { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual EssayAnswer EssayAnswer { get; set; }
        public virtual MCQAnswer MCQAnswer { get; set; }
        public virtual TFAnswer TFAnswer { get; set; }
    }
}
