//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gb_raw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsAllowed
    {
        public int studentsAllowedID { get; set; }
        public int examID { get; set; }
        public bool isTaken { get; set; }
        public Nullable<int> result { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual SysUser SysUser { get; set; }
    }
}
